version: 2.1

orbs:
  python: circleci/python@1.5.0

jobs:
  build-and-test:
    docker:
      - image: cimg/python:3.6
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: pip
          pip-dependency-file: test-requirements.txt
      - python/install-packages:
          pkg-manager: pip-dist
      - run:
          name: Run tests
          command: pytest

workflows:
  merge:
    jobs:
      - build-and-test
