version: 2.1

orbs:
  python: circleci/python@1.5.0

jobs:
  test:
    parameters:
      python-version:
        type: string
    docker:
      - image: cimg/python:<< parameters.python-version >>
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: pip
          pip-dependency-file: test-requirements.txt
      - python/install-packages:
          pkg-manager: pip-dist
      - run:
          name: Run tests
          command: pytest

workflows:
  matrix-test:
    jobs:
      - test:
          matrix:
            parameters:
              python-version: ["3.7", "3.8", "3.9"]
